apiVersion: v1
kind: Service
metadata:
  name: odcs-swagger
  namespace: {{ .Values.namespace }}
  labels:
    app: odcs-swagger
spec:
  type: {{ .Values.swagger.service.type }}
  selector:
    app: odcs-swagger
  ports:
  - port: {{ .Values.swagger.service.port }}
    targetPort: {{ .Values.swagger.service.targetPort }}
    protocol: TCP
    name: http

