apiVersion: v1
kind: Service
metadata:
  name: odcs-postgrest
  namespace: {{ .Values.namespace }}
  labels:
    app: odcs-postgrest
spec:
  type: {{ .Values.postgrest.service.type }}
  selector:
    app: odcs-postgrest
  ports:
  - port: {{ .Values.postgrest.service.port }}
    targetPort: {{ .Values.postgrest.service.targetPort }}
    protocol: TCP
    name: http

