# PostgREST configuration
# Connect to the Postgres database created by the docker-compose `db` service

db-uri = "postgres://postgres:postgres@db:5432/postgres"
db-schema = "public"
db-anon-role = "postgrest"
server-port = 3000
openapi-mode = "follow-privileges"

